apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: pigeons
  name: pigeons
  namespace: kaiser
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pigeons
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: pigeons
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - env:
        
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: pigeons-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: pigeons-configmap
                  key: REDIS_PORT
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: pigeons-configmap
                  key: KAFKA_HOST
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: pigeons-configmap
                  key: KAFKA_PORT
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: pigeons-configmap
                  key: KAFKA_CLIENT_ID
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: pigeons-configmap
                  key: KAFKA_GROUP_ID
            - name: MQTT_HOST
              valueFrom:
                configMapKeyRef:
                  name: pigeons-configmap
                  key: MQTT_HOST
            - name: MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  name: pigeons-configmap
                  key: MQTT_PORT
#=================================================================================================================
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pigeons-secrets
                  key: REDIS_PASSWORD
          image: '10.1.0.14:8081/comfortech/pigeons:v1.0'
          name: pigeons
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}