apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: iguana
  name: iguana-service
  namespace: kaiser
spec:
  ports:
    - name: "2000"
      port: 2001
      targetPort: 2000
  selector:
    io.kompose.service: iguana
status:
  loadBalancer: {}