apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: pyrador
  name: pyrador
  namespace: kaiser
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pyrador
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: pyrador
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: pyrador-configmap
                  key: APP_PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: pyrador-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: pyrador-configmap
                  key: REDIS_PORT
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: pyrador-configmap
                  key: KAFKA_HOST
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: pyrador-configmap
                  key: KAFKA_PORT
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: pyrador-configmap
                  key: KAFKA_CLIENT_ID
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: pyrador-configmap
                  key: KAFKA_GROUP_ID
            - name: AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: pyrador-secrets
                  key: AUTH_KEY
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pyrador-secrets
                  key: REDIS_PASSWORD
          image: '10.1.0.14:8081/comfortech/pyrador:v1.0'
          name: pyrador
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}