apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://10.1.0.15:41887
  name: kind-comfortech-staging
contexts:
- context:
    cluster: kind-comfortech-staging
    user: kind-comfortech-staging
  name: kind-comfortech-staging
current-context: kind-comfortech-staging
kind: Config
preferences: {}
users:
- name: kind-comfortech-staging
  user:
    client-certificate-data: 
    client-key-data: 
